name: build
description: build

inputs:
  working-dir-app:
    description: 'set the current application working directory'
    required: true
    default: './worldpay-raft-connector'

runs:
  using: "composite"
  steps:
    - name: Install
      working-directory: ${{ inputs.working-dir-app }}
      shell: bash
      run: |
        npm install
    - name: build
      working-directory: ${{ inputs.working-dir-app }}
      shell: bash
      run: |
        npm run prettier
        npm run lint
        npm run build
